inherit_from: ../.rubocop.yml

Style/GlobalVars:
  Enabled: false

Style/IndentArray:
  Enabled: false

Style/AlignHash:
  Enabled: false

Style/VariableNumber:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

LineLength:
  Enabled: false
